In [19]:
import numpy as np 
import numdifftools as nd 
obj = lambda x: (1- 2*x[0] + 3*x[1])**2 + x[0]**2 + (x[1]-1)**2
def grad(x): 
    return (10*x[0] - 12*x[1] - 4), (-12*x[0] + 20*x[1] + 4)
eps = 1e-3
x0 = np.zeros((2) , dtype=int)
k = 0
soln = [x0]
x = soln[k]
err = np.linalg.norm(grad(x))
a = 1e-2

while err >= eps:
    x = x - np.multiply(grad(x),a)
    soln.append(x)
    err = np.linalg.norm(grad(x))
    k=k+1

soln
#(10*x[0] - 12*x[1] - 4), (-12*x[0] + 20*x[1] + 4)


[array([0, 0]),
 array([ 0.04, -0.04]),
 array([ 0.0712, -0.0672]),
 array([ 0.096016, -0.085216]),
 array([ 0.11618848, -0.09665088]),
 array([ 0.13297153, -0.10337809]),
 array([ 0.147269  , -0.10674589]),
 array([ 0.1597326 , -0.10772443]),
 array([ 0.17083241, -0.10701163]),
 array([ 0.18090777, -0.10510942]),
 array([ 0.19020386, -0.1023786 ]),
 array([ 0.19889804, -0.09907842]),
 array([ 0.20711883, -0.09539497]),
 array([ 0.21495955, -0.09146172]),
 array([ 0.22248819, -0.08737423]),
 array([ 0.22975446, -0.0832008 ]),
 array([ 0.23679492, -0.0789901 ]),
 array([ 0.24363662, -0.07477669]),
 array([ 0.25029975, -0.07058496]),
 array([ 0.25679958, -0.066432  ]),
 array([ 0.26314778, -0.06232965]),
 array([ 0.26935345, -0.05828598]),
 array([ 0.27542379, -0.05430637]),
 array([ 0.28136464, -0.05039424]),
 array([ 0.28718087, -0.04655164]),
 array([ 0.29287658, -0.04277961]),
 array([ 0.29845537, -0.0390785 ]),
 array([ 0.30392042, -0.03544815]),
 array([ 0.3092746 , -0.03188807]),
